# your domain
domain: example.com
port:                 # default 12580

# source list file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
cron-interval:        #  v0.5.x default 60 min
crontime:            #  v0.4.x default 60 min. Deprecated in the newiest version

# speed test
speedtest: false      # default false. Warning: this will consume large network resources.
speedtest-interval:   # default 12 hours
connection:           # default 5.
timeout:              # default 10 (seconds).

# active proxy check
active-interval:      # default 1h
active-frequency:     # default 100/h

# cloudflare api
cf_email: ""
cf_key: ""
