# your domain
domain: example.com
port:             # default 12580

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# (optinal) postgresql database info
database_url: ""

# interval between each execution
cron-interval:            # default 60 min

# speedtest
speedtest-interval:   # default 12 hours
speedtest:            # default false. Warning: this will consume large net resource.
connection:           # default 5.
timeout:              # default 10 (seconds).

# active proxy check
active-interval:      # default 1h
active-frequency:     # default 80/h


# (optinal) cloudflare api
cf_email: ""
cf_key: ""
